## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up JDK 17 with Gradle cache
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle  # Use Gradle's cache instead of Maven

      # Make Gradle wrapper executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the project using Gradle
      - name: Build
        run: ./gradlew build
